[package]
name = "project1"
version = "1.0.0"
authors = []

[addresses]
ole_dapp="0xd9bff56c4c93e3833677b1c4915e9a3d4fa9593ef8430b4dca03ea360e470de4"
dapp = "0x6d07dbae9458f0e635b207b11145a951609517d4335c6dbb21f373fe68191936"
admin1="0xeeeb01ae130cecc693d410641b2b79328fa0ba025c2ec00405b4823ad9221d56"
admin2="0xa51ce864e04cfbc35c06085e273b7be5b6ca047605bceb1ec6be8d6295c7ae7f"

<<<<<<< Updated upstream

[dev-addresses]
=======
pontem_address="0x190d44266241744264b964a37b8f09863167a12d3e70cda39376cfb4e3561e12"
>>>>>>> Stashed changes

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
#git = "https://gitee.com/WGB5445/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.Liquidswap]
local = "./Liquidswap"

[dev-dependencies]
