[package]
name = "project1"
version = "1.0.0"
authors = []

[addresses]
dapp = "0x199095a1b1b0f7cfe8d1dcfed29c35956583561c1251f17dd4806c18cc34d387"
admin1="0xeeeb01ae130cecc693d410641b2b79328fa0ba025c2ec00405b4823ad9221d56"
admin2="0xa51ce864e04cfbc35c06085e273b7be5b6ca047605bceb1ec6be8d6295c7ae7f"


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
#git = "https://gitee.com/WGB5445/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
